[drainage]
swdra    = 1
dramet   = 3
swdivd   = 1
swdislay = 0
nrlevs   = 2
cofani   = [1.0, 1.0, 1.0, 1.0]

[[drainage.levels]]
swdtyp      = 2
swallo      = 1
zbotdr      = -140.0
drares      = 130.0
infres      = 150.0
L           = 40.0
owltab_file = "owltab1.csv"

[[drainage.levels]]
swdtyp      = 2
swallo      = 3
zbotdr      = -20.0
drares      = 50.0
infres      = 40.0
L           = 15.0
owltab_file = "owltab2.csv"
